[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2021"
authors = ["Tâmer Pinheiro Cuba <tamercuba@gmail.com>"]
license = "MIT"

[lib]
name = "rust_blockchain"
path = "src/lib.rs"

[dependencies]
hex = "0.3.2"
crypto-hash = "0.3.3"